# Generated by Django 5.2.16 on 2026-07-26 12:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('type', models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=10)),
                ('account', models.CharField(choices=[('APGB', 'APGB Bank'), ('SBI', 'SBI Bank'), ('CASH', 'Cash')], max_length=10)),
                ('category', models.CharField(default='Other', max_length=50)),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
    ]
