# Generated by Django 5.2.16 on 2026-07-31 16:15

from django.db import migrations


DEFAULT_CATEGORIES = [
    ('Food', '🍔'),
    ('Shopping', '🛒'),
    ('Utilities', '⚡'),
    ('Rent', '🏠'),
    ('Travel', '✈️'),
    ('Salary', '💰'),
    ('Investment', '📈'),
    ('Self Transfer', '🔄'),
    ('Entertainment', '🎬'),
    ('Interest', '💳'),
    ('Refund/Cashback', '💸'),
    ('Other', '📦'),
]


def seed_categories(apps, schema_editor):
    Category = apps.get_model('tracker', 'Category')
    for name, emoji in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(
            name=name,
            defaults={'emoji': emoji, 'is_default': True}
        )


def reverse_seed(apps, schema_editor):
    Category = apps.get_model('tracker', 'Category')
    Category.objects.filter(is_default=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_category_alter_transaction_date'),
    ]

    operations = [
        migrations.RunPython(seed_categories, reverse_seed),
    ]
