# Generated by Django 5.2.16 on 2026-09-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_seed_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='to_account',
            field=models.CharField(blank=True, choices=[('APGB', 'APGB Bank'), ('SBI', 'SBI Bank'), ('CASH', 'Cash')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer')], max_length=10),
        ),
    ]
