# Generated by Django 5.2.16 on 2026-09-03 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_add_hdfc_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='contact_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('INCOME', 'Income'), ('EXPENSE', 'Expense'), ('TRANSFER', 'Transfer'), ('LENT', 'Lent'), ('BORROWED', 'Borrowed'), ('REPAYMENT_RECEIVED', 'Repayment Received'), ('REPAYMENT_MADE', 'Repayment Made')], max_length=20),
        ),
    ]
